[context.development.environment]
    HUGO_VERSION = "0.129.0"
    DART_SASS_VERSION = "1.75.0"

[dev]
    framework = "#custom"
    command = "npm run dev"
    targetPort = 1313
    functions = "functions"
    publish = "public"

[build]
    publish = "public"
    command = "npm run build"
[build.environment]
    HUGO_VERSION = "0.129.0"
    DART_SASS_VERSION = "1.75.0"
    
